package com.brimmatech.dto.activity;

import lombok.Getter;

@Getter
public final class ActivityTitleConstants {

    public static final String NOTE_ADDED_TYPE = "NOTE_ADDED";
    public static final String NOTE_ADDED_DESC = "Note Added";
    public static final String NOTE_UPDATED_TYPE = "NOTE_UPDATED";
    public static final String NOTE_UPDATED_DESC = "Note Updated";
    public static final String TASK_UPDATED_TYPE = "TASK_UPDATED";
    public static final String TASK_UPDATED_DESC = "Task Updated";
    public static final String TASK_ADDED_TYPE = "TASK_ADDED";
    public static final String TASK_ADDED_DESC = "Task Added";
    public static final String LEAD_UPDATED_TYPE = "LEAD_UPDATED";
    public static final String LEAD_UPDATED_DESC = "Lead Updated";
    public static final String LEAD_STATUS_UPDATED_TYPE = "LEAD_STATUS_UPDATED";
    public static final String LEAD_STATUS_UPDATED_DESC = "Lead Status Updated";
    public static final String LEAD_CREATED_TYPE = "LEAD_CREATED";
    public static final String LEAD_CREATED_DESC = "Lead Created";
    public static final String AUTO_INTRO_SMS_TYPE = "AUTO_INTRO_TEXT";
    public static final String AUTO_INTRO_SMS_DESC = "Auto Intro Text Sent";
    public static final String AUTO_INTRO_CALL_TYPE = "AUTO_INTRO_CALL";
    public static final String AUTO_CALL_COMPLETED_DESC = "Auto Intro Outbound Call Contacted";
    public static final String AUTO_CALL_MISSED_DESC = "Auto Intro Outbound Call Unanswered";
    public static final String AUTO_CALL_DECLINED_DESC = "Auto Intro Outbound Call Declined";
    public static final String AUTO_CALL_FAILED_DESC = "Auto Intro Outbound Call Failed";
    public static final String MANUAL_CALL_COMPLETED_DESC = "Outgoing Call Contacted";
    public static final String MANUAL_CALL_MISSED_DESC = "Outgoing Call Unanswered";
    public static final String MANUAL_CALL_DECLINED_DESC = "Outgoing Call Declined";
    public static final String MANUAL_CALL_FAILED_DESC = "Outgoing Call Failed";
    public static final String AUTO_EMAIL_TYPE = "AUTO_EMAIL";
    public static final String AUTO_EMAIL_DESC = "Auto Intro Email Sent";
    public static final String EMAIL_SENT_TYPE = "EMAIL_SENT";
    public static final String EMAIL_SENT_DESC = "Email sent";
    public static final String QUOTE_SENT_TYPE = "QUOTE_SENT";
    public static final String QUOTE_FAILED_TYPE = "QUOTE_FAILED";
    public static final String QUOTE_SENT_DESC = "Quote sent";
    public static final String TEXT_SENT_TYPE = "TEXT_SENT";
    public static final String TEXT_SENT_DESC = "Text Sent";
    public static final String AUTO_TEXT_SENT_TYPE = "AUTO_TEXT_SENT";
    public static final String AUTO_TEXT_SENT_DESC = "Auto Text Sent";
    public static final String TEXT_RECEIVED_TYPE = "TEXT_RECEIVED";
    public static final String TEXT_RECEIVED_DESC = "Text Received";
    public static final String AUTO_INTRO_EMAIL_TYPE = "INTRO_EMAIL";
    public static final String INVITE_EMAIL_TYPE = "INVITE_EMAIL";
    public static final String INVITE_EMAIL_FAILED_TYPE = "INVITE_EMAIL_FAILED";
    public static final String INVITE_EMAIL_DESC = "Invite to Apply Email Sent";
    public static final String INVITE_SMS_TO_LEAD_TYPE = "INVITE_SMS";
    public static final String INVITE_SMS_TO_LEAD_DESC = "Invite to Apply Text Sent";
    public static final String AUTO_SENT_EMAIL_TYPE = "AUTO_EMAIL_SENT";
    public static final String AUTO_SENT_EMAIL_DESC = "Auto Email Sent";
    public static final String ATTEMPT_EMAIL_TYPE = "ATTEMPT_EMAIL";
    public static final String ATTEMPT_EMAIL_FAILED_TYPE = "ATTEMPT_EMAIL_FAILED";
    public static final String LEAD_REASSIGN = "LEAD_REASSIGNED";
    public static final String LEAD_REASSIGN_DESC = "Lead Reassigned";
    public static final String AUTO_INTRO_EMAIL_OPENED_DESC = "Auto Intro Email Opened";
    public static final String AUTO_INTRO_EMAIL_OPENED_TYPE = "INTRO_EMAIL_OPENED";
    public static final String QUOTE_EMAIL_OPENED_DESC = "Quote Opened";
    public static final String QUOTE_EMAIL_OPENED_TYPE = "QUOTE_OPENED";
    public static final String AUTO_INTRO_EMAIL_FAILED_TYPE = "INTRO_EMAIL_FAILED";
    public static final String AUTO_INTRO_EMAIL_FAILED_DESC = "Auto Intro Email Failed";
    public static final String EMAIL_DELIVERY_FAILED_TYPE = "EMAIL_DELIVERY_FAILED";
    public static final String EMAIL_DELIVERY_FAILED_DESC = "Email Delivery Failed";
    public static final String LEAD_ARCHIVED_TYPE = "LEAD_ARCHIVED";
    public static final String LEAD_ARCHIVED_DESC = "Lead Archived";
    public static final String LEAD_UNARCHIVED_TYPE = "LEAD_UNARCHIVED";
    public static final String LEAD_UNARCHIVED_DESC = "Lead Unarchived";
    public static final String AUTO_CALL_ATTEMPTED_DESC = "Auto Intro Call Attempt Completed";
    public static final String MANUAL_CALL_ATTEMPTED_DESC = "Call Attempt Completed";
    public static final String QUOTE_COPY_SENT_DESC = "Quote Copy Sent To";
    public static final String AUTO_EMAIL_COPY_DESC = "Auto Intro Email Copy Sent To";
    public static final String EMAIL_COPY_SENT_DESC = "Email Copy Sent To";
    public static final String INVITE_EMAIL_COPY_DESC = "Invite to Apply Email Copy Sent To";
    public static final String AUTO_SENT_EMAIL_COPY_DESC = "Auto Email Copy ";
    public static final String AUTO_INTRO_EMAIL_COPY_FAILED_DESC = "Auto Intro Email Copy To";
    public static final String AUTO_INTRO_CALL_SCHEDULED = "INTRO_CALL_SCHEDULED";
    public static final String AUTO_INTRO_CALL_SCHEDULED_DESC = "Auto Intro Outbound Call Scheduled";
    public static final String CAMPAIGN_ACTIVATED_TYPE = "CAMPAIGN_ACTIVATED";
    public static final String CAMPAIGN_ACTIVATED_DES = "Campaign Activated";

}
